exports.hobbies = [
  { value: 'reading', label: 'Reading' },
  { value: 'traveling', label: 'Traveling' },
  { value: 'cooking', label: 'Cooking' },
  { value: 'sports', label: 'Sports' },
  { value: 'music', label: 'Music' },
  { value: 'gardening', label: 'Gardening' },
  { value: 'photography', label: 'Photography' },
  { value: 'painting', label: 'Painting' },
  { value: 'writing', label: 'Writing' },
  { value: 'dancing', label: 'Dancing' },
  { value: 'hiking', label: 'Hiking' },
  { value: 'fishing', label: 'Fishing' },
  { value: 'knitting', label: 'Knitting' },
  { value: 'yoga', label: 'Yoga' },
  { value: 'baking', label: 'Baking' },
  { value: 'drawing', label: 'Drawing' },
  { value: 'running', label: 'Running' },
  { value: 'cycling', label: 'Cycling' },
  { value: 'swimming', label: 'Swimming' },
  { value: 'birdwatching', label: 'Birdwatching' },
  { value: 'camping', label: 'Camping' },
  { value: 'volunteering', label: 'Volunteering' },
  { value: 'board games', label: 'Board Games' },
  { value: 'puzzles', label: 'Puzzles' },
  { value: 'gaming', label: 'Gaming' },
  { value: 'collecting', label: 'Collecting' },
  { value: 'origami', label: 'Origami' },
  { value: 'model building', label: 'Model Building' },
  { value: 'scrapbooking', label: 'Scrapbooking' },
  { value: 'calligraphy', label: 'Calligraphy' },
];

exports.interests = [
  { value: 'technology', label: 'Technology' },
  { value: 'science', label: 'Science' },
  { value: 'arts', label: 'Arts' },
  { value: 'fitness', label: 'Fitness' },
  { value: 'travel', label: 'Travel' },
  { value: 'food', label: 'Food' },
  { value: 'movies', label: 'Movies' },
  { value: 'fashion', label: 'Fashion' },
  { value: 'literature', label: 'Literature' },
  { value: 'history', label: 'History' },
  { value: 'politics', label: 'Politics' },
  { value: 'photography', label: 'Photography' },
  { value: 'architecture', label: 'Architecture' },
  { value: 'design', label: 'Design' },
  { value: 'finance', label: 'Finance' },
  { value: 'philosophy', label: 'Philosophy' },
  { value: 'education', label: 'Education' },
  { value: 'environment', label: 'Environment' },
  { value: 'health', label: 'Health' },
  { value: 'entrepreneurship', label: 'Entrepreneurship' },
  { value: 'psychology', label: 'Psychology' },
  { value: 'spirituality', label: 'Spirituality' },
  { value: 'DIY', label: 'DIY' },
  { value: 'martial arts', label: 'Martial Arts' },
  { value: 'music', label: 'Music' },
  { value: 'theater', label: 'Theater' },
  { value: 'travel', label: 'Travel' },
  { value: 'pets', label: 'Pets' },
  { value: 'science fiction', label: 'Science Fiction' },
  { value: 'anime', label: 'Anime' },
];

exports.qualifications = [
  { value: 'high_school', label: 'High School Diploma' },
  { value: 'associate', label: 'Associate Degree' },
  { value: 'bachelor', label: 'Bachelor\'s Degree' },
  { value: 'master', label: 'Master\'s Degree' },
  { value: 'doctorate', label: 'Doctorate (Ph.D.)' },
  { value: 'professional', label: 'Professional Degree (MD, JD, etc.)' },
  { value: 'cert_cs', label: 'Certificate in Computer Science' },
  { value: 'cert_ds', label: 'Certificate in Data Science' },
  { value: 'diploma_eng', label: 'Diploma in Engineering' },
  { value: 'diploma_ba', label: 'Diploma in Business Administration' },
  { value: 'diploma_gd', label: 'Diploma in Graphic Design' },
  { value: 'diploma_marketing', label: 'Diploma in Marketing' },
  { value: 'diploma_nursing', label: 'Diploma in Nursing' },
  { value: 'diploma_education', label: 'Diploma in Education' },
  { value: 'cert_pm', label: 'Certificate in Project Management' },
  { value: 'cert_hr', label: 'Certificate in Human Resources' },
  { value: 'cert_fp', label: 'Certificate in Financial Planning' },
  { value: 'cert_wd', label: 'Certificate in Web Development' },
  { value: 'cert_culinary', label: 'Certificate in Culinary Arts' },
  { value: 'cert_dm', label: 'Certificate in Digital Marketing' },
  { value: 'cert_hs', label: 'Certificate in Health and Safety' },
  { value: 'diploma_psych', label: 'Diploma in Psychology' },
  { value: 'diploma_env_sc', label: 'Diploma in Environmental Science' },
  { value: 'diploma_journalism', label: 'Diploma in Journalism' },
  { value: 'diploma_sw', label: 'Diploma in Social Work' },
  { value: 'cert_cyber', label: 'Certificate in Cybersecurity' },
  { value: 'cert_ai', label: 'Certificate in Artificial Intelligence' },
  { value: 'diploma_fine_arts', label: 'Diploma in Fine Arts' },
  { value: 'cert_na', label: 'Certificate in Network Administration' },
  { value: 'cert_fitness', label: 'Certificate in Fitness Training' },
];